#! /xampp/htdocs/command-line php

<?php

use Symfony\Component\Console\Application;
use \Acme\NewCommand;
require 'vendor/autoload.php';

$app = new Application('My-Command','1.0');

$app->add(new Acme\RenderCommand);


//$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();