#! /xampp/htdocs/command-line php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use \Symfony\Component\Console\Output\OutputInterface;
use \Symfony\Component\Console\Input\InputArgument;
require 'vendor/autoload.php';

$app = new Application('My-Command','1.0');

$app->register('sayHelloTo')
    ->setDescription('Offer Greeting To My App')
    ->addArgument('name',InputArgument::OPTIONAL,'Your Name')
    ->setCode(function (InputInterface $input,OutputInterface $output)
    {
        $message = 'Hello , ' .$input->getArgument('name');
       $output->writeln("<info>{$message}</info>");
    });

$app->run();